//This file is generated by bin/hook.js
var template = require('template');
module.exports = {

  CSS: {
    
      'youtube_playback': '.clappr-youtube-playback{position:absolute;height:"100%";width:"100%";display:block}',
    
  }
};
